spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/busconnectdb
    username: busconnect_user
    password: 'BusConnect_pass2025'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
