
server:
  # 1. Puerto del servicio
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:busconnectdb}
    username: ${DB_USERNAME:busconnect_user}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          '[format_sql]': true
          '[default_schema]': auth_service

    config:
      activate:
        on-profile: docker

    messages:
      basename: messages
      encoding: UTF-8
      fallback-to-system-locale: false

    profiles:
      active: docker

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha

  logging:
    level:
      '[com.busconnect.userservice]': DEBUG
      '[org.hibernate.SQL]': DEBUG
      '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

# 3. CONFIGURACIÓN DEL CLIENTE EUREKA (Descubrimiento de Servicios), pendiente de conectar servicio
eureka:
  client:
    # URL del servidor de Eureka (asume el host 'eureka-service' en Docker Compose)
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    # Habilitar el registro y la búsqueda de servicios
    register-with-eureka: false
    fetch-registry: false
  instance:
    # Configuración esencial para entornos Docker
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

# 4. CONFIGURACIÓN DE LOGGING
logging:
  level:
    # Nivel de información para el framework de Spring
    org.springframework: INFO
    # Nivel de debug para ver las peticiones que realiza el Feign Client
    com.busconnect.auth.client.UserServiceClient: DEBUG

